US001: Add Crud Actions and Views to Category Model
iamurtazo/BookStoreApp pull request #1
Opened 2024-05-01 06:50 UTC by iamurtazo

2024-05-01 08:31 UTC, SamanKingDotNetDeveloper requested changes

2024-05-01 08:31 UTC, SamanKingDotNetDeveloper commented on BookStoreApp/Views/Category/Index.cshtml
> +                    Category Name
@Html.DisplayNameFor(model => model.Name)

2024-05-01 09:17 UTC, iamurtazo commented on BookStoreApp/Views/Category/Index.cshtml
> +                    Category Name
Got it)

2024-05-04 13:01 UTC, SamanKingDotNetDeveloper approved these changes

2024-05-04 13:28 UTC, merged